HelloPerson = "Hello {{.Name}}"

[ResponseNotAllowedEmptyMessage]
description = "{{.Key}} 不允许空!"

[TokenValidationError]
other = "请求非法，请退出重试"
[TokenValidationErrorExpired]
other = "登录状态已过期，请重新登录"
[TokenValidationErrorNotValidYet]
other = "请求非法，请退出重试"
[TokenHandleError]
other = "请求非法，请退出重试"
[TokenEmptyError]
other = "无权限访问"