HelloPerson = "Hello {{.Name}}"

[ResponseNotAllowedEmptyMessage]
other = "{{.Key}} is not allowed empty!"

[TokenValidationError]
other = "Request is illegal, please quit retry"
[TokenValidationErrorExpired]
other = "Login status has expired, please log in again"
[TokenValidationErrorNotValidYet]
other = "Request is illegal, please quit retry"
[TokenHandleError]
other = "Request is illegal, please quit retry"
[TokenEmptyError]
other = "No access"
